require('dotenv').config()
const express=require("express")
// const products=require("./Data/Products")
const app=express()
const router=require("./Router/productRouter")
const UserRouter=require("./Router/userRouting")
const OrderRouter=require("./Router/orderRouting")
require("./db/database")

app.use(express.json())
const Errorhandle=require("./middleWare/errMidle")
app.use(Errorhandle)
app.use(router)
app.use("/api/orders",OrderRouter)
app.use("/api/users",UserRouter)
app.listen(3500)